### PR TITLE
Added HelpRequest menu to Nav Bar

### LINKED ISSUE #26: Add HelpRequest menu to nav bar
- [x] There is pull down menu on the Nav Bar with the label HelpRequests.
- [x] When the label is clicked, we see a menu with two options: "List HelpRequests" and "Create HelpRequests".
- [x] When the "List HelpRequests" option is selected, the browser window goes to the route /helprequests/list
- [x] When the "Create HelpRequests" option is selected, the browser window goes to the route /helprequests/create
- [x] There is full test coverage (npm coverage) for the new code in
      `AppNavBar.js`
- [x] There is full mutation test coverage (npm stryker) for the new code in
      `AppNavBar.js`

### PR DESCRIPTION
**Pull request by ilai-ucsb**
- Added HelpRequest menu to Nav Bar with list and create buttons.
- Added frontend test that passes test coverage and mutation testing.
- Closes #26

### CODE REVIEW

**Comment by wesleykam** [comment]
From my understanding, I think only Admins should be able to see Create (and List) while regular users can only see the List option. So I think they need to be separated in both files like 2 separate user_role cases and 2 separate tests.

**Comment by ilai-ucsb** [comment]
> From my understanding, I think only Admins should be able to see Create (and List) while regular users can only see the List option. So I think they need to be separated in both files like 2 separate user_role cases and 2 separate tests.

**Comment by ilai-code** [comment]
@wesleykam I'm not sure how the staff wanted it to be implemented, but I implemented the backend of HelpRequest such that Users can post and get. I thought that Users should be able to post a new help request and the admins would manage which help request should be there. That's why I allow Users to access both list and create in the frontend.

**Review by wesleykam — COMMENTED** [review]
Makes sense! Lgtm!

**Review by wesleykam — APPROVED** [review]

**Pull request merged**
